name: Update README with latest tweets

on:
  issues:
    types: [opened, edited, deleted]

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: 最新のIssuesを取得してREADMEを更新
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const issues = await github.paginate(
              github.rest.issues.listForRepo, 
              {
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: 'open',
                sort: 'created',
                direction: 'desc'
              }
            );
            const filteredIssues = issues.filter(issue => !issue.pull_request);
            const tweets = filteredIssues.map(issue => `- ${issue.title}`).join('\n');
            const readmeContent = `# プロフィール\n\n## 最新のつぶやき\n\n${tweets}`;
            fs.writeFileSync('README.md', readmeContent);

      - name: 変更をコミット
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update README with latest tweets"
          file_pattern: README.md
          github.token: ${{ secrets.GITHUB_TOKEN }}